Theory Assignment

In [ ]:
# 1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


## NumPy is a fundamental library for scientific computing and data analysis in Python.
     # It provides efficient multi-dimensional arrays and a vast collection of mathematical functions to operate on these arrays.

    # Purpose:
           # Efficient Numerical Operations:
                          # NumPy's arrays are optimized for numerical computations, offering significantly faster performance compared to Python's built-in lists.
           # Broad Range of Mathematical Functions:
                          # NumPy provides a comprehensive set of mathematical functions, including trigonometric, logarithmic, exponential, and statistical operations.
           # Linear Algebra and Fourier Transforms:
                          # NumPy efficiently handles linear algebra operations like matrix multiplication, inversion, and eigenvalue decomposition, as well as Fourier transforms for signal processing and data analysis.
     # Advantages:
           # Performance:
                        # NumPy's optimized array operations and efficient algorithms make it much faster than Python's standard data structures for numerical computations.
           # Memory Efficiency:
                        # NumPy arrays are stored in contiguous memory blocks, reducing memory overhead and improving performance.
           # Integration with Other Libraries:
                        # NumPy seamlessly integrates with other scientific computing libraries like SciPy, Matplotlib, and Pandas, making it a versatile tool for data analysis and visualization.
           # Ease of Use:
                        # NumPy's intuitive syntax and extensive documentation make it easy to learn and use, even for those with limited programming experience.

  # NumPy Enhances Python's Capabilities:
           # Efficient Numerical Operations:
                    # NumPy provides optimized array operations that are much faster than Python's built-in lists, making it ideal for tasks like matrix multiplication, statistical calculations, and signal processing.
           # Broad Range of Mathematical Functions:
                    # NumPy offers a comprehensive set of mathematical functions, allowing you to perform complex calculations without writing custom code.
           # Linear Algebra and Fourier Transforms:
                    # NumPy's efficient implementation of linear algebra and Fourier transform operations enables you to solve mathematical problems and analyze data more effectively.
           # Integration with Other Libraries:
                    # NumPy's seamless integration with other scientific computing libraries like SciPy, Matplotlib, and Pandas extends its capabilities and makes it a powerful tool for data analysis and visualization.

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


##  np.mean() and np.average() in NumPy are both used to calculate the average of an array, but they have slight differences in their functionality.Here’s a comparison:
    # np.mean():
           # Purpose: Computes the arithmetic mean (average) of array elements.
           # Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=<no value>, where=<no value>)
           # Parameters:
                      # array: Input array.
                      # axis: Axis along which the means are computed. Default is to compute the mean of the flattened array.
                      # dtype: Data type to use in computing the mean.
                      # out: Alternate output array to place the result.
                      # keepdims: If set to True, the reduced axes are left in the result as dimensions with size one.
                      # where: Elements to include in the mean calculation.
            # Example:
                    import numpy as np

                    array = np.array([5,6,7,8,9])
                    mean_value = np.mean(array)
                    print("Mean value:", mean_value)    # Output: Mean value: 7.0
    # np.average():
           # Purpose: Computes the weighted average of array elements if weights are provided; otherwise, it calculates the arithmetic mean.
           # Syntax: np.average(array, axis=None, weights=None, returned=False)
           # Parameters:
                      # array: Input array.
                      # axis: Axis along which the averages are computed.
                      # weights: An array of weights associated with the values in the input array.
                      # returned: If True, returns a tuple containing the average and the sum of the weights.
           # Example:
                    import numpy as np

                    array = [1, 2, 3, 4, 5]
                    weights = [0.1, 0.2, 0.3, 0.4, 0.5]
                    weighted_avg = np.average(array, weights=weights)
                    print(weighted_avg)      # Output: 3.6666666666666665

    # When to Use Which:
                  # Use np.mean():
                               # When you need to calculate the simple arithmetic mean of an array without considering any weights.
                  # Use np.average():
                                # When you need to calculate a weighted average, where different elements contribute differently to the final average.

In [ ]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

## Reversing a NumPy array can be done using several methods, each suitable for different scenarios.
    # Here are some common methods to reverse arrays along different axes, with examples for both 1D and 2D arrays:

       # 1. Reversing along the First Axis (Rows):
                        # np.flip(array, axis=0): Reverses the array along the first axis (rows).
                        # Example:
                                import numpy as np

                                array = np.array([[1, 2, 3],
                                                  [4, 5, 6]])

                                reversed_array = np.flip(array, axis=0)
                                print(reversed_array)     # Output: [[4 5 6]
                                                                     [1 2 3]]
       # 2. Reversing along the Second Axis (Columns):
                        # np.flip(array, axis=1): Reverses the array along the second axis (columns).
                        # Example:
                                 import numpy as np

                                 array = np.array([[1, 2, 3],
                                                   [4, 5, 6]])

                                 reversed_array = np.flip(array, axis=1)
                                 print(reversed_array)     # Output: [[3 2 1]
                                                                      [6 5 4]]
       # 3. Reversing along Multiple Axes:
                        # np.flip(array, axis=(0, 1)): Reverses the array along both the first and second axes.
                        # Example:
                                 import numpy as np

                                 array = np.array([[1, 2, 3],
                                                   [4, 5, 6]])

                                 reversed_array = np.flip(array, axis=(0, 1))
                                 print(reversed_array)     # Output: [[6 5 4]
                                                                      [3 2 1]]
       # 4. Reversing a 1D Array:
                        # np.flip(array): Reverses the 1D array.
                        # Example:
                                 import numpy as np

                                 array = np.array([1, 2, 3])

                                 reversed_array = np.flip(array)
                                 print(reversed_array)      # Output: [3 2 1]
   # Here are examples of 1D and 2D arrays:
           # 1D Array:
                     array = [1, 2, 3, 4, 5]
                     print(array)     # Output: [1, 2, 3, 4, 5]
           # 2D Array:
                     array = [[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]
                     print(array)    # Output: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

## Determining Data Type of Elements in a NumPy Array:
      # In NumPy, each array has a specific data type associated with its elements.
      # This data type determines the size of each element in memory and the operations that can be performed on them.
   # Methods to Determine Data Type:
           # 1. dtype Attribute:
                             # The most direct way is to access the dtype attribute of the array:
                                                                                               import numpy as np

                                                                                               array = np.array([1, 2, 3, 4])
                                                                                               print(array.dtype)    # Output: int32
           # 2. type() Function:
                              # You can use the built-in type() function to get the type of the array itself, but this will return numpy.ndarray:
                                                                                                                          print(type(array))   # Output: <class 'numpy.ndarray'>
           # 3. isinstance() Function:
                                   # If you need to check if an array's elements are of a specific data type, use isinstance():
                                                                                                                     print(isinstance(array.item(0), int))  # Output: True

   # Importance of Data Types in Memory Management and Performance
      # Memory Management:
                   # Efficient Storage:
                                    # NumPy allocates memory for an array based on its data type. Using the appropriate data type can significantly reduce memory usage.
                                    #  For example, storing integers as int8 instead of int64 can save a lot of space.
                   # Memory Alignment:
                                   # NumPy often aligns elements in memory to improve performance. Mismatched data types can lead to inefficient memory access.
      # Performance:
                   # Optimized Operations:
                                        # NumPy's operations are optimized for specific data types. Using the correct data type can result in faster computations.
                                        # For instance, operations on floating-point numbers are generally slower than those on integers.
                   # Avoid Type Conversions:
                                          # Unnecessary type conversions can introduce overhead and slow down computations.
                                          # Choosing the right data type upfront can prevent these conversions.

In [ ]:
# 5.  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

## NumPy ndarrays:
                # In NumPy, an ndarray (N-dimensional array) is a powerful data structure used for numerical computations.
                # It is a grid of values, all of the same type, indexed by a tuple of non-negative integers.
                # The number of dimensions is defined by the array’s ndim attribute, and the shape of the array is defined by the shape attribute.
    # Key Features of NumPy ndarrays:
               # 1. Homogeneous Data Type:
                                           # All elements within a NumPy ndarray must be of the same data type (e.g., int32, float64, bool).
                                           # This ensures efficient memory usage and optimized operations.
               # 2. Fixed Size:
                             # The size of a NumPy ndarray is fixed once created. This allows for efficient memory allocation and optimized algorithms.
               # 3. Multi-Dimensional:
                                    # ndarrays can have any number of dimensions, from 0-dimensional scalars to higher-dimensional arrays like matrices and tensors.
               # 4. Vectorized Operations:
                                        # NumPy supports vectorized operations, allowing you to perform operations on entire arrays without explicit loops.
                                        # This significantly improves performance.
               # 5. Broadcasting:
                               # NumPy has a powerful broadcasting mechanism that allows arrays of different shapes to be compatible for arithmetic operations.
               # 6. Indexing and Slicing:
                                       # You can access and manipulate elements within ndarrays using indexing and slicing operations, similar to Python lists.
               # 7. Shape and Size:
                                  # Each ndarray has a shape, which is a tuple representing the size of the array along each dimension.
                                  # The size of an array is the total number of elements.

     # Differences from Standard Python Lists:
              # While both NumPy ndarrays and Python lists can store collections of elements, they have significant differences:
                      # Data Type:
                                # NumPy ndarrays require all elements to have the same data type, while Python lists can store elements of mixed types.
                      # Performance:
                                  # NumPy ndarrays are typically much faster than Python lists for numerical operations due to vectorization and optimized implementations.
                      # Memory Efficiency:
                                         # NumPy ndarrays are often more memory-efficient than Python lists, especially for large arrays.
                      # Functionality:
                                    # NumPy ndarrays provide a wide range of functions and methods specifically designed for numerical computations, such as mathematical operations, linear algebra, and Fourier transforms.

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

## Performance Benefits of NumPy Arrays Over Python Lists
    # When it comes to large-scale numerical operations, NumPy arrays offer several significant performance benefits over standard Python lists:
       # 1. Vectorization:
                   # NumPy's Strength:
                                    # NumPy arrays are designed for efficient vectorized operations.
                                    # This means that operations can be performed on entire arrays at once, without the need for explicit loops.
                   # Python Lists' Weakness:
                                    # Python lists require explicit loops for most numerical operations, which can be slow, especially for large datasets.
       # 2. Data Type Homogeneity:
                   # NumPy's Advantage:
                                   # All elements in a NumPy array must be of the same data type. This allows for efficient memory allocation and optimized operations.
                   # Python Lists' Drawback:
                                   # Python lists can store elements of mixed data types, which can lead to inefficient memory management and slower operations.
       # 3.  Memory Layout:
                   # NumPy's Efficiency:
                                   # NumPy arrays are stored in contiguous memory blocks, which is ideal for efficient access and manipulation.
                   # Python Lists' Inefficiency:
                                   # Python lists may not always be stored in contiguous memory, which can lead to slower access times.
       # 4. Optimized C Implementation:
                   # NumPy's Speed:
                                 # Many NumPy operations are implemented in C, which is a much faster language than Python. This provides significant performance gains.
                   # Python Lists' Slowness:
                                 # Python lists are implemented in Python, which can be slower for computationally intensive tasks.
       # 5. Broadcasting:
                  # NumPy's Flexibility:
                                 # NumPy's broadcasting mechanism allows for efficient operations on arrays of different shapes.
                  # Python Lists' Limitations:
                                 # Python lists lack a built-in broadcasting mechanism, making it more difficult to perform operations on arrays of different sizes.
   # Example:
            import numpy as np
            import time

            n = 1000000
            np_array = np.random.rand(n)
            py_list = list(np_array)

            start = time.time()
            np_result = np_array * 2
            end = time.time()
            np_time = end - start

            start = time.time()
            py_result = [x * 2 for x in py_list]
            end = time.time()
            py_time = end - start

            print("NumPy time:", np_time)
            print("Python list time:", py_time)

            # Output: NumPy time: 0.0030679702758789062
                      Python list time: 0.060079097747802734

In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

## Comparing vstack() and hstack() in NumPy:
       # Both vstack() and hstack() are functions in NumPy used to stack arrays, but they do so in different orientations.

       # vstack(): Stacks arrays vertically (row-wise).
       # hstack(): Stacks arrays horizontally (column-wise).

       # vstack():
                # Functionality: Stacks arrays in sequence vertically (row-wise).
                # Usage: Takes a sequence of arrays and combines them along the first axis (axis 0).
                # Requirement: The input arrays must have the same shape along all but the first axis.
                # Example:
                         import numpy as np

                         array1 = np.array([[1, 2],
                                           [3, 4]])

                         array2 = np.array([[5, 6],
                                           [7, 8]])

                         stacked_array = np.vstack((array1, array2))
                         print(stacked_array)
                         # Output: [[1 2]
                                    [3 4]
                                    [5 6]
                                    [7 8]]
       # hstack():
                # Functionality: Stacks arrays in sequence horizontally (column-wise).
                # Usage: Takes a sequence of arrays and combines them along the second axis (axis 1).
                # Requirement: The input arrays must have the same shape along all but the second axis.
                # Example:
                         array1 = np.array([[1, 2],
                                           [3, 4]])

                         array2 = np.array([[5, 6],
                                           [7, 8]])

                         stacked_array = np.hstack((array1, array2))
                         print(stacked_array)
                         # Output: [[1 2 5 6]
                                    [3 4 7 8]]
    # Key Differences:
              # Orientation: vstack() stacks arrays vertically, while hstack() stacks them horizontally.
              # Axis: vstack() operates along axis=0, and hstack() operates along axis=1.
              # Use Cases: Use vstack() when you want to add rows to an array, and hstack() when you want to add columns.

In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

## The fliplr() and flipud() methods in NumPy are used to flip arrays, but they do so in different directions. Here’s a detailed explanation:
        # fliplr():
                 # Function: numpy.fliplr(m)
                 # Description: Flips the array in the left/right direction (i.e., horizontally)
                 # Effect: Reverses the order of columns in each row.
                 # Applicable Dimensions: Requires the input array to be at least 2-dimensional.
                 # Example:
                          import numpy as np
                          A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
                          print(np.fliplr(A))
                          # Output: [[3 2 1]
                                     [6 5 4]
                                     [9 8 7]]
        # flipud():
                 # Function: numpy.flipud(m)
                 # Description: Flips the array in the up/down direction (i.e., vertically).
                 # Effect: Reverses the order of rows.
                 # Applicable Dimensions: Can be used on arrays of any dimension.
                 # Example:
                          import numpy as np
                          A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
                          print(np.flipud(A))
                          # Output: [[7 8 9]
                                     [4 5 6]
                                     [1 2 3]]
     # Effects on Different Array Dimensions:
              # 1D Array: Both fliplr() and flipud() will reverse the order of elements.
              # 2D Array: fliplr() reverses the order of elements in each row, while flipud() reverses the order of elements in each column.
              # 3D Array: fliplr() reverses the order of elements in each row within each layer, while flipud() reverses the order of elements in each column within each layer.
     # Key Points:
              # fliplr() and flipud() are useful for reversing the order of elements in specific dimensions of an array.
              # The choice between fliplr() and flipud() depends on the desired flipping direction (last axis or first axis).
              # Understanding the effects of these methods on different array dimensions is essential for effective data manipulation in NumPy.

In [ ]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

## The array_split() method in NumPy is used to split an array into multiple sub-arrays. It provides a flexible way to partition data based on various requirements.
       # Functionality:
             # Function: numpy.array_split(ary, indices_or_sections, axis=0)
             # Description: Splits an array into multiple sub-arrays along a specified axis.
             # Parameters:
                       # ary: The input array to be split.
                       # indices_or_sections: If an integer, it indicates the number of equal or near-equal sub-arrays to create. If a list of sorted integers, it specifies the points at which to split the array.
                       # axis: The axis along which to split the array (default is 0).
      # Handling Uneven Splits:
              # When the array length is not evenly divisible by the number of splits, the array_split() method distributes the extra elements as evenly as possible among the sub-arrays.
              # The first sub-array will have one more element than the rest if the remainder is 1.
              # If the remainder is 2, the first two sub-arrays will have one more element each.
              # This ensures that the sub-arrays are balanced and the data is partitioned fairly.
          # Example:
                   import numpy as np

                   arr = np.array([1, 2, 3, 4, 5, 6, 7])

                   sub_arrays = np.array_split(arr, 3)

                   print(sub_arrays)
                   # Output: [array([1, 2, 3]), array([4, 5]), array([6, 7])]
                   # In this example, the array is split into 3 sub-arrays. The first two sub-arrays have 3 elements each, while the last sub-array has 2 elements, ensuring a balanced distribution.

In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

##  Vectorization and broadcasting are fundamental concepts in NumPy that significantly enhance the efficiency of array operations.
    # They allow for element-wise operations on entire arrays without the need for explicit loops, leading to substantial performance improvements.

    # Vectorization:
             # Definition:
                        # Vectorization is the process of performing operations on entire arrays without using explicit loops.
                        # NumPy is optimized for vectorized operations, which are executed in highly efficient compiled code.
             # Benefits:
                       # Speed: Vectorized operations are much faster than equivalent Python loops, especially for large arrays.
                       # Readability: Vectorized code is often more concise and easier to understand.
                       # Memory Efficiency: Vectorized operations can be more memory-efficient than explicit loops.
              # Example:
                       import numpy as np

                       arr1 = np.array([1, 2, 3, 4])
                       arr2 = np.array([5, 6, 7, 8])
                       result = arr1 + arr2
                       print("Array 1:")
                       print(arr1)    # Output: Array 1:
                                                [1 2 3 4]
                       print("Array 2:")
                       print(arr2)    # Output: Array 2:
                                                [5 6 7 8]
                       print("Result after Vectorized Addition:")
                       print(result)   # Output: Result after Vectorized Addition:
                                                 [ 6  8 10 12]
    # Broadcasting:
              # Definition:
                           # Broadcasting is a set of rules that NumPy follows to perform operations between arrays of different shapes.
                           # NumPy automatically stretches the smaller array to match the shape of the larger array before performing the operation.
              # Rules of Broadcasting:
                        # 1. Array with smaller ndim than the other is prepended with '1' in its shapem.
                        # 2. Size in each dimension of the output shape is maximum of the input sizes in that dimensionm
                        # 3. An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
                        # 4. If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

                        # A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true.
                          # 1. Arrays have exactly the same shape.
                          # 2. Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
                          # 3.Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.
              # Example:
                       import numpy as np
                       arr = np.array([1, 2, 3, 4, 5])
                       multiplier = np.array([2])
                       result = arr * multiplier
                       print(result)       # Output: [ 2  4  6  8 10]

      # Vectorization and Broadcasting Contribute to Efficiency:
                  # Optimized Operations: NumPy's underlying implementation leverages highly efficient algorithms and hardware-specific optimizations for vectorized operations.
                  # Reduced Overhead: Avoiding explicit loops eliminates the overhead of loop control and function calls.
                  # Memory Access Patterns: Vectorized operations often lead to more efficient memory access patterns, improving cache utilization.
                  # Parallelism: Many NumPy operations can be parallelized, taking advantage of multiple cores or GPUs.

Practical Assignment

In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

##
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

transposed_array = array.T
print("Transposed array:")
print(transposed_array)

Original array:
[[51 43 54]
 [ 4 21  5]
 [36 22 54]]
Transposed array:
[[51  4 36]
 [43 21 22]
 [54  5 54]]


In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

##
import numpy as np

array_1d = np.arange(1, 11)   # Generate a 1D array with 10 elements
print("Original 1D array:")
print(array_1d)

array_2x5 = array_1d.reshape(2, 5)     # Reshape the 1D array into a 2x5 array
print("\nReshaped to 2x5 array:")
print(array_2x5)

array_5x2 = array_2x5.reshape(5, 2)    # Reshape the 2x5 array into a 5x2 array
print("\nReshaped to 5x2 array:")
print(array_5x2)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

##
import numpy as np

array_4x4 = np.random.rand(4, 4)     # Create a 4x4 array with random float values
print("Original 4x4 array:")
print(array_4x4)

array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)    # Add a border of zeros around the 4x4 array to 6x6 array
print("\nArray with border of zeros (6x6):")
print(array_6x6)

Original 4x4 array:
[[0.29092552 0.77972896 0.74619218 0.44008945]
 [0.51681578 0.02510807 0.13201096 0.20774521]
 [0.63521096 0.67886534 0.37665545 0.9789081 ]
 [0.66503137 0.67557897 0.77342951 0.83085819]]

Array with border of zeros (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.29092552 0.77972896 0.74619218 0.44008945 0.        ]
 [0.         0.51681578 0.02510807 0.13201096 0.20774521 0.        ]
 [0.         0.63521096 0.67886534 0.37665545 0.9789081  0.        ]
 [0.         0.66503137 0.67557897 0.77342951 0.83085819 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

##
import numpy as np

array = np.arange(10, 61, 5)   # Create an array of integers from 10 to 60 with a step of 5
print("Array with integers from 10 to 60 with a step of 5:")
print(array)

Array with integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

##
import numpy as np

array = np.array(['python', 'numpy', 'pandas'])    # Create a NumPy array of strings
print("Original array:")
print(array)

uppercase_array = np.char.upper(array)      # Apply different case transformations
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
swapcase_array = np.char.swapcase(array)
capitalize_array = np.char.capitalize(array)

print("\nUppercase transformation:")
print(uppercase_array)

print("\nLowercase transformation:")
print(lowercase_array)

print("\nTitle case transformation:")
print(titlecase_array)

print("\nSwap case transformation:")
print(swapcase_array)

print("\nCapitalized transformation:")
print(capitalize_array)

Original array:
['python' 'numpy' 'pandas']

Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase transformation:
['python' 'numpy' 'pandas']

Title case transformation:
['Python' 'Numpy' 'Pandas']

Swap case transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Capitalized transformation:
['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

##
import numpy as np

words = np.array(["suman", "saikat", "pwskills", "bird"])   # Create a NumPy array of words

spaced_words = np.char.join(' ', words)   # Insert a space between each character of every word

print("Original Array:")
print(words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array:
['suman' 'saikat' 'pwskills' 'bird']

Array with Spaces Between Characters:
['s u m a n' 's a i k a t' 'p w s k i l l s' 'b i r d']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

##
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])        # Create two 2D NumPy arrays
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = np.add(array1, array2)     # Perform element-wise addition

subtraction = np.subtract(array1, array2)    # Perform element-wise subtraction

multiplication = np.multiply(array1, array2)     # Perform element-wise multiplication

division = np.divide(array1, array2)    # Perform element-wise division

print("\nArray 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

##
import numpy as np

identity_matrix = np.identity(5)    # Create a 5x5 identity matrix

diagonal_elements = np.diag(identity_matrix)    # Extract the diagonal elements

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [1]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

##
import numpy as np

random_integers = np.random.randint(0, 1001, size=100)    # Generate an array of 100 random integers between 0 and 1000

def is_prime(n):          # Function to check if a number is prime
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in random_integers if is_prime(num)]     # Find all prime numbers in the array

print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(prime_numbers)

Random Integers:
[827 175 354 593 815  32 225 149 599 868 170 662 391 376  58 673 537 512
   3 388 665 243 264 818 407 706  17 652 723 479  50 698 228 329 967 833
 268 297 457 125 617 271 259 236 982 530 247 589 138 427 495 989 518 201
 247 477 697 294 605 856 567 331  44 374 978 691 873 878 798 652 950  54
 371 702 711 336 866 842 221 523 388 283 978 824 649 540 171 131 729 778
 557 976 391 881 572 655 120 775 929 276]

Prime Numbers:
[827, 593, 149, 599, 673, 3, 17, 479, 967, 457, 617, 271, 331, 691, 523, 283, 131, 557, 881, 929]


In [4]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

##
import numpy as np

daily_temperatures = np.random.randint(20, 50, size=30)  # Create a NumPy array with random temperatures for 30 days
                                                         # Temperatures between 20°C and 40°C

weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]     # Calculate weekly averages

print("Daily Temperatures:")
print(daily_temperatures)
print("Weekly Averages:")
print(weekly_averages)

Daily Temperatures:
[25 41 39 37 37 45 47 27 42 23 34 27 22 48 44 37 38 33 38 38 25 34 38 38
 33 31 24 46 35 37]
Weekly Averages:
[38.714285714285715, 31.857142857142858, 36.142857142857146, 34.857142857142854, 36.0]
